In [1]:
print("Question 1")
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Question 1
Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [2]:
print("Question 2")
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Question 2
Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [8]:
print("Question 3")
import numpy as np
x = np.array([[0, 10, 20], [30,40, 50]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Question 3
Original array: 
[[ 0 10 20]
 [30 40 50]]
Values bigger than 10 = [20 30 40 50]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [11]:
print("Question 4")
import numpy as np 
A=np.array([[1, 2, 3]])
B=np.array([[1, 2, 3]])
C=np.add(A, B)
C

Question 4


array([[2, 4, 6]])

In [12]:
print("Question 5")
import numpy as np
x=np.array([[4, 5, 6]])
y=x.mean()
y

5.0